import Link from 'next/link';import {matches,players,transfers,stories,clubs,articles} from '@/lib/data';import {ArrowLeft,CalendarDays,Sparkles,Flame,Star,TrendingUp,MessageCircle,ShieldCheck,Activity} from 'lucide-react';
export function PageTitle({kicker,title,sub}:{kicker:string,title:string,sub?:string}){return <div className='mb-6'><span className='chip active'>{kicker}</span><h1 className='mt-4 text-4xl font-black md:text-6xl'>{title}</h1>{sub&&<p className='mt-3 max-w-3xl text-lg leading-8 text-white/55'>{sub}</p>}</div>}
export function Section({title,sub,children}:{title:string,sub?:string,children:React.ReactNode}){return <section className='mt-8'><div className='mb-4 flex items-end justify-between gap-4'><div><h2 className='text-2xl font-black md:text-3xl'>{title}</h2>{sub&&<p className='mt-1 text-white/50'>{sub}</p>}</div><button className='chip'>عرض الكل <ArrowLeft size={14}/></button></div>{children}</section>}
export function MatchCard({m=matches[0],large=false}:{m?:any,large?:boolean}){return <Link href={`/match/${m.id}`} className={`glass card block overflow-hidden p-5 ${large?'min-h-[360px]':''}`}><div className='flex items-center justify-between'><span className='chip active'>{m.league}</span><span className='chip'>{m.status} · {m.time}</span></div><div className='my-7 grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center'><Team name={m.home}/><div><div className='text-4xl font-black'>{m.score}</div><div className='mt-2 text-xs text-white/45'>Match Center</div></div><Team name={m.away}/></div><div className='grid grid-cols-3 gap-2 text-center text-sm'><div className='metric'><b>{m.prob[0]}%</b><p className='text-white/45'>فوز الأول</p></div><div className='metric'><b>{m.prob[1]}%</b><p className='text-white/45'>تعادل</p></div><div className='metric'><b>{m.prob[2]}%</b><p className='text-white/45'>فوز الثاني</p></div></div><p className='mt-4 rounded-3xl bg-white/[.045] p-4 leading-7 text-white/62'>{m.story}</p></Link>}
function Team({name}:{name:string}){return <div className='grid place-items-center gap-3'><div className='grid h-20 w-20 place-items-center rounded-[28px] border border-white/10 bg-gradient-to-br from-white/15 to-white/5 text-3xl font-black'>{name[0]}</div><b className='text-xl'>{name}</b></div>}
export function MatchGrid(){return <div className='grid gap-4 lg:grid-cols-3'>{matches.map(m=><MatchCard key={m.id} m={m}/>)}</div>}
export function DNABars({data=matches[0].dna}:{data?:Record<string,number>}){return <div className='space-y-4'>{Object.entries(data).map(([k,v])=><div key={k}><div className='mb-2 flex justify-between text-sm'><b>{k}</b><span className='text-emerald-300'>{v}%</span></div><div className='bar'><span style={{width:`${v}%`}}/></div></div>)}</div>}
export function PlayerGrid(){return <div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4'>{players.map(p=><Link href={`/player/${encodeURIComponent(p.name)}`} className='glass card p-5' key={p.name}><div className='flex items-start justify-between'><div className='grid h-16 w-16 place-items-center rounded-3xl bg-white/10 text-2xl font-black'>{p.name[0]}</div><span className='chip text-emerald-300'>{p.trend}</span></div><h3 className='mt-4 text-xl font-black'>{p.name}</h3><p className='text-white/50'>{p.club} · {p.pos}</p><div className='mt-5 flex items-center justify-between'><b className='text-3xl text-emerald-300'>{p.rating}</b><span className='text-sm text-white/45'>Football Genome</span></div><div className='mt-3 grid grid-cols-5 gap-1'>{p.dna.map((d,i)=><div key={i} className='h-16 rounded-full bg-white/10' style={{background:`linear-gradient(to top, rgba(18,242,163,.9) ${d}%, rgba(255,255,255,.08) ${d}%)`}}/>)}</div></Link>)}</div>}
export function ClubGrid(){return <div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4'>{clubs.map(c=><Link href={`/club/${c.id}`} className='glass card p-5' key={c.id}><div className='flex justify-between'><div className='grid h-16 w-16 place-items-center rounded-3xl bg-emerald-300/15 text-3xl font-black text-emerald-300'>{c.name[0]}</div><span className='chip'><Sparkles size={14}/> Mood {c.mood}%</span></div><h3 className='mt-4 text-2xl font-black'>{c.name}</h3><p className='text-white/50'>Form: {c.form}</p><div className='mt-5'><DNABars data={c.dna}/></div></Link>)}</div>}
export function TransferList(){return <div className='grid gap-4 lg:grid-cols-3'>{transfers.map(t=><div className='glass card p-5' key={t.player}><div className='flex items-center justify-between'><span className='chip'><Flame size={14}/> {t.tier}</span><b className='text-2xl text-emerald-300'>{t.confidence}%</b></div><h3 className='mt-4 text-2xl font-black'>{t.player}</h3><p className='text-white/55'>{t.from} ← {t.to}</p><div className='my-4 bar'><span style={{width:`${t.confidence}%`}}/></div><p className='leading-7 text-white/60'>{t.reason}</p></div>)}</div>}
export function Stories(){return <div className='grid gap-4 lg:grid-cols-3'>{stories.map(s=><article className='hero-card card p-6' key={s.title}><span className='chip active'>{s.tag} · {s.year}</span><h3 className='mt-5 text-3xl font-black'>{s.title}</h3><p className='mt-3 leading-8 text-white/60'>{s.text}</p><button className='btn btn-ghost mt-5'>افتح الفيلم الكروي</button></article>)}</div>}
export function CalendarDemo(){const days=['السبت','الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة'];return <div className='glass card p-5'><div className='mb-4 flex items-center justify-between'><h3 className='text-2xl font-black'><CalendarDays className='ml-2 inline'/> تقويم المباريات</h3><span className='chip active'>يونيو 2026</span></div><div className='grid grid-cols-7 gap-2 text-center text-sm text-white/45'>{days.map(d=><b key={d}>{d}</b>)}</div><div className='mt-2 grid grid-cols-7 gap-2'>{Array.from({length:28}).map((_,i)=><div className={`calendar-day ${[4,11,17,22].includes(i)?'border-emerald-300/40 bg-emerald-300/10':''}`} key={i}><b>{i+1}</b>{[4,11,17,22].includes(i)&&<p className='mt-3 rounded-full bg-emerald-300 px-2 py-1 text-xs font-black text-slate-950'>3 مباريات</p>}</div>)}</div></div>}
export function IntelligenceRail(){return <aside className='sidebar desktop-only space-y-4'><div className='glass card p-5'><h3 className='text-xl font-black'><Activity className='ml-2 inline text-emerald-300'/> نبض المدرج</h3><div className='mt-4 space-y-3'>{['ثقة جماهير الأهلي 91%','رادار صلاح +12%','الكلاسيكو الأكثر تداولاً'].map(x=><div className='soft rounded-2xl p-3 text-white/65' key={x}>{x}</div>)}</div></div><div className='glass card p-5'><h3 className='text-xl font-black'><ShieldCheck className='ml-2 inline text-cyan-300'/> ميزات حصرية</h3><div className='mt-4 flex flex-wrap gap-2'>{['Football Genome','Match Movie','Fan Mood','AI Scout','ذاكرة المباراة'].map(x=><span className='chip' key={x}>{x}</span>)}</div></div></aside>}
export function ArticleGrid(){return <div className='grid gap-4 md:grid-cols-3'>{articles.map(a=><article className='glass card p-5' key={a.title}><span className='chip'><Star size={14}/>{a.tag}</span><h3 className='mt-4 text-2xl font-black'>{a.title}</h3><p className='mt-3 leading-7 text-white/55'>محتوى تحليلي قابل للإدارة لاحقاً من Admin Studio ومرتبط بالبيانات الحية.</p></article>)}</div>}
export function AdminPreview(){return <div className='grid gap-4 lg:grid-cols-4'>{['المباريات','المقالات','اللاعبون','ذاكرة المباراة','الانتقالات','التوقعات','المجتمع','الإعدادات'].map((x,i)=><div className='glass card p-5' key={x}><span className='chip'>{i+1}</span><h3 className='mt-4 text-2xl font-black'>{x}</h3><p className='mt-2 text-white/50'>إدارة ديناميكية Demo الآن، API لاحقاً.</p></div>)}</div>}
export function CommunityBlocks(){return <div className='grid gap-4 lg:grid-cols-3'>{['من يفوز بالكلاسيكو؟','أفضل لاعب عربي هذا الأسبوع؟','هل يحتاج الأهلي لمهاجم؟'].map((q,i)=><div className='glass card p-5' key={q}><span className='chip'><MessageCircle size={14}/> استطلاع</span><h3 className='mt-4 text-2xl font-black'>{q}</h3><div className='mt-4 space-y-3'><div><b>اختيار الجمهور</b><div className='bar mt-2'><span style={{width:`${70-i*12}%`}}/></div></div><div><b>الرأي الآخر</b><div className='bar mt-2'><span style={{width:`${30+i*12}%`}}/></div></div></div></div>)}</div>}
